/**
 * Global Constants for Krishna Valley Real Estate ERP
 */

export const USER_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  SALES_MANAGER: 'SALES_MANAGER',
  SALES_AGENT: 'SALES_AGENT',
  ACCOUNTS_MANAGER: 'ACCOUNTS_MANAGER',
  SITE_ENGINEER: 'SITE_ENGINEER',
  CUSTOMER: 'CUSTOMER'
};

export const UNIT_STATUS = {
  AVAILABLE: 'AVAILABLE',
  HOLD: 'HOLD',
  BOOKED: 'BOOKED',
  BLOCKED: 'BLOCKED',
  SOLD: 'SOLD',
  HANDED_OVER: 'HANDED_OVER'
};

export const UNIT_TYPES = {
  FLAT_1BHK: '1BHK',
  FLAT_2BHK: '2BHK',
  FLAT_3BHK: '3BHK',
  FLAT_4BHK: '4BHK',
  STUDIO: 'STUDIO',
  SERVICE_APARTMENT: 'SERVICE_APARTMENT',
  PENTHOUSE: 'PENTHOUSE',
  VILLA: 'VILLA',
  COMMERCIAL_SHOP: 'COMMERCIAL_SHOP',
  OFFICE_SPACE: 'OFFICE_SPACE',
  RESIDENTIAL_PLOT: 'RESIDENTIAL_PLOT'
};

export const LEAD_STATUS = {
  NEW: 'NEW',
  CONTACTED: 'CONTACTED',
  SITE_VISIT_SCHEDULED: 'SITE_VISIT_SCHEDULED',
  SITE_VISIT_COMPLETED: 'SITE_VISIT_COMPLETED',
  NEGOTIATION: 'NEGOTIATION',
  BOOKED: 'BOOKED',
  LOST: 'LOST'
};

export const PAYMENT_MODES = {
  BANK_TRANSFER: 'BANK_TRANSFER',
  CHEQUE: 'CHEQUE',
  UPI: 'UPI',
  DEMAND_DRAFT: 'DEMAND_DRAFT',
  CASH: 'CASH',
  PAYMENT_GATEWAY: 'PAYMENT_GATEWAY'
};

export const PAYMENT_PLAN_TYPES = {
  CONSTRUCTION_LINKED: 'CONSTRUCTION_LINKED',
  DOWN_PAYMENT: 'DOWN_PAYMENT',
  TIME_LINKED: 'TIME_LINKED',
  CUSTOM: 'CUSTOM'
};

export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  PAID: 'PAID',
  OVERDUE: 'OVERDUE',
  CANCELLED: 'CANCELLED'
};
